### ISSUE TITLE
Can you please share Accuracy Numbers ?

### ISSUE THREAD

**Issue by themitigater** [ahmetozlu/signature_extractor#1]

**Comment by ahmetozlu** [comment]
What kind of accuracy do you mean? 

I have not performed any special training process, I have developed this project on top of traditional image processing techniques (such as connected component analysis, morphological filters and so on). Therefore, since there are not any training process, there are not any accuracy but you can calculate the accuracy considering your test dataset. The test accuracy depends on the test data so it is not so meaningful but yes, some benchmark handwritten signature dataset can be used for it. I just added it inside my future works. Thanks...
