### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by qfabio83** [ahmetozlu/signature_extractor#2]
Please, is difficult to develope a function that return true if a signature is present and false if not?

I need to understand if a document has been signed.

Thanks a lot

**Comment by ahmetozlu** [comment]
This is not a bug, you can easily add your need as a new feature so your modified program can understand that any signatures are detected or not... 

You can process the output image and if the output image contains any connected pixels then you should return "true" otherwise you should return "false".. That's all...
