### ISSUE TITLE
a better signature detection?

### ISSUE THREAD

**Issue by mixianbuguoqiao** [ahmetozlu/signature_extractor#5]
Excuse me,
After testing, I found that it didn't work well in many cases. Is there a better signature detection model?

**Comment by netsensei** [comment]
Well, I found that it works best with images having a high contrast and enough sharpness. If you work with low-resolution scans that were heavily compressed with a lossy algorithm like JPG, then the detection won't work well.

In my case, I don't have to actually extract a signature, but merely detect them. So, if the algorithm already gets me a few pixels that are part of a signature, that's enough. 

What I did up front was using ImageMagick to turn images in to Black/White (-type Grayscale) and then sharpen them to smooth out blurring and artefacts from JPG of low resolution scanning.

I've toyed with a few samples and it's just enough to get going.

**Comment by ahmetozlu** [comment]
Actually, this project just a sample to show how can the signatures be detected & extracted on scanned documents using traditional image processing algorithms. Since juts traditional image processing algorithms were used, the accuracy and success rate is limited unfortunately. The success of the pipe-line can be improved by adding some pre-processing. However, if you need more, you should train a detection model based deep learning, this would be the best approach to get the best results.
